### ISSUE TITLE
addToClasspath after version 10...

### ISSUE THREAD

**Issue by EasyG0ing1** [fuinorg/utils4j#38]
Hello,

Forgive me, I know very little about this library. All I know is that I use it when I create a JavaFX application that exists solely in the operating systems system tray so that the application does not create an icon in the taskbar. 

I use it in a Launcher class like this:

```
import org.fuin.utils4j.Utils4J;
import java.io.File;

public class Launcher {
  public static void main(String[] args) {
      Utils4J.addToClasspath("file:///" + System.getProperty("java.home") + File.separator + "lib" + File.separator + "jfxrt.jar");
      Main.main(args);
  }
}
```

However, If I specify any version of the library beyond 0.10.1, the addToClassPath method is no longer there.

So, my question is; how would I accomplish the same thing that I'm doing, with the newer version of the library?

Thank you

**Comment by michael-schnell** [comment]
Starting with Java 11, it's no longer possible to add something to the classpath like it was possible before. 

Therefore the method was dropped in the newer versions:

- 0.12.x (or later) = Java 11 with new jakarta namespace
- 0.11.x = Java 11 before namespace change from 'javax' to 'jakarta'
- 0.9.x/0.10.x = Java 8 = Last versions with "addToClasspath(..)"

Does this answer your question?

**Comment by EasyG0ing1** [comment]
@michael-schnell - YES, I believe it does ... what you're telling me is that versions 0.10.x and below are for Java 8 while 
everything above that is for the newer versions of Java ... so I just need to continue using the version I'm using (0.10.1) in my Java 8 projects.

**Comment by michael-schnell** [comment]
Yes, if you use 0.10.1, everything should work as expected.
